### ISSUE TITLE
Question: will screen auto-lock again after X minutes of (local) inactivity when remote disconnects?

### ISSUE THREAD

**Issue by MestreLion** [jikamens/allow-locked-remote-desktop#12]
First, congrats for the amazing extension! Really appreciate!

In your README you have a very fair warning:

> if someone is allowed to connect to the screen remotely and unlock it, then the local computer display is also unlocked, not just the remote display

Question: If extension is enabled, after disconnecting from remote, will the regular inactivity timeout kick in and re-lock the local display again after X minutes? Assuming no local mouse/keyboard use, of course, that's exactly what you warned about.

Or because I've unlocked from remote (thanks to this extension) now the local display will be unlocked indefinitely? Hopefully it's the former! 

Either way, this could be better clarified in the README.

**Comment by jikamens** [comment]
Behaves exactly the same as if you unlocked the screen in person. If you have an idle timeout configured then the screen will lock again after it is idle for that period of time.

**Comment by MestreLion** [comment]
Nice! Glad to know!
