### ISSUE TITLE
Not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by anthonypillot** [jikamens/allow-locked-remote-desktop#3]
> First of all, I was very happy to see that someone was concerned by the problem of the lock screen. So, thank you so much.

Unfortunately, after several attempts, the extension refuses to stay in "activated" status. It automatically switches to disabled mode when I refresh the installed extensions page. And the connection via RDP is impossible.

Do you have a solution? Thanks in advance!

`uname -a` result:
`Linux Ubuntu 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by jikamens** [comment]
I am using the add-on with no trouble on Ubuntu 22.04 so I can't explain this.

The only suggestion I have is to open the "Extensions" app (not extensions.gnome.org) and make sure that the rocker switch at the top which enables/disables all extensions is enabled.

**Comment by anthonypillot** [comment]
I tried many different settings just to be sure.
I will now try with the application. I'll keep you posted.
Thank you for your very quick reply @jikamens !

**Comment by anthonypillot** [comment]
Hi again, first of all your extension works better with the "Extension" application. So thank you!
But I think I got it wrong: I was searching for something which can launch the RDP server without log me into the session, in a "headless mode". Not on the locked screen.

To be more understandable: I'm working away from home, so I'm booting my computer on `Wake On Wan`, and I need to enter the password of my session, physically, to let the RDP server start. I've guessed that your extension'll boot, or letting boot, the RDP server. It seems that it's just to not disconnect the RDP server and not boot RDP server.

So.. hope I'll find a workaround. Thanks for your answer btw!

**Comment by AndrielF** [comment]
> Hi again, first of all your extension works better with the "Extension" application. So thank you! But I think I got it wrong: I was searching for something which can launch the RDP server without log me into the session, in a "headless mode". Not on the locked screen.
> 
> To be more understandable: I'm working away from home, so I'm booting my computer on `Wake On Wan`, and I need to enter the password of my session, physically, to let the RDP server start. I've guessed that your extension'll boot, or letting boot, the RDP server. It seems that it's just to not disconnect the RDP server and not boot RDP server.
> 
> So.. hope I'll find a workaround. Thanks for your answer btw!

Did you figure out how to solve this problem? One way I found to work around it is by using AnyDesk.

**Comment by bugith** [comment]
Won't systemctl --user restart gnome-remote-desktop do the job ?

**Comment by AndrielF** [comment]
> Won't systemctl --user restart gnome-remote-desktop do the job ?

No, the issue is when a system restart is required and the remote connection only comes back up after you physically enter the password on the computer

**Comment by bugith** [comment]
Sorry AndrielF
I read this command this afternoon but I didn't try it yet after a reboot or a closed session. I dreamed it was the ultimate workaround to gnome-remote-desktop restrictions/regressions over Vino after I discovered the Allow Locked Remote Desktop extension by Jonathan. I'm still trying to have the remote screen to autolock immediately as before on disconnect or network failure.

**Comment by AndrielF** [comment]
> Sorry AndrielF
> I read this command this afternoon but I didn't try it yet after a reboot or a closed session. I dreamed it was the ultimate workaround to gnome-remote-desktop restrictions/regressions over Vino after I discovered the Allow Locked Remote Desktop extension by Jonathan. I'm still trying to have the remote screen to autolock immediately as before on disconnect or network failure.

You don't need to say sorry :)
And to autolock when lose connection:
<img width="611" alt="Screenshot 2023-05-01 at 17 26 22" src="https://user-images.githubusercontent.com/114447037/235525091-48b26941-14a1-4fae-a087-4f6584b58f79.png">
<img width="1280" alt="Screenshot 2023-05-01 at 17 26 39" src="https://user-images.githubusercontent.com/114447037/235525078-56cda197-504c-4b4d-8439-7572a6ce3aa8.png">

**Comment by bugith** [comment]
Hi @AndrielF
I have both `/org/gnome/remote-access/lock-screen-on-disconnect` & `/org/gnome/deskop/screensaver/ubuntu-lock-on-suspend`  set to true and ~not-false~ respectively. This doesn't work... which is surprising for the first key and not surprising for the second one (as suspend is not triggered/always desirable on RDP disconnect). I'll dig on remmina/avnc side to see if I find something.
