### ISSUE TITLE
lock screen on disconnect

### ISSUE THREAD

**Issue by bugith** [jikamens/allow-locked-remote-desktop#5]
Hi Jonathan
Thank you very much for this extension that makes my Ubuntu 22.04 nearly as convenient as 16.04.
I'm not sure this is close related to your extension, but the option in dconf /org/gnome/desktop/remote-access/lock-screen-on-disconnect=true is not honored/does not work anymore. This is the next concern I meet in the path to workaround the regression introduced when upgrading from Vino to gnome-remote-desktop that prevents remotely login to a locked session. I'm still using VNC from Remmina, Wayland 22.04 on each side. I read gnome and Remmina want to drop VNC, I'll try RDP later. 
Did you meet this too ?

**Comment by jikamens** [comment]
I never used that option and don't know anything about it.

**Comment by bugith** [comment]
It was/is? intended to lock the remote screen when we close the connection. I don't know if it still appears in freshly installed OS. Don't worry, I guess gnome just forgot this use case.
