### ISSUE TITLE
Remmina won't update server key (RDP server Ubuntu 22.04 remmina 1.4.25)

### ISSUE THREAD

**Issue by bugith** [jikamens/allow-locked-remote-desktop#6]
Nearly every time I connect to my rdp server (through ssh tunnel) I get this warning (gimp translated/redacted) :
I checked the key in the server, it matches the "new key" shown in remmina and is the same each time I connect.
![Capture d’écran du 2023-05-16 18-08-21](https://github.com/jikamens/allow-locked-remote-desktop/assets/6240207/4ee63d17-1cbe-4c04-b3d1-b9c2255e4456)

Please, which local file does Remmina check against when this warning happens? I know I can globally "trust all certificates" or disable certificates check on a per peer basis, but... I'd rather like not (not sure this is advised/recommended practice)
Many thanks in advance.

**Comment by jikamens** [comment]
Please stop filing general gnome remote desktop support requests in this repository. This is not a support forum, it's the issue database for one small gnome extension that does one small thing.
