### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by darkblaze69** [jikamens/allow-locked-remote-desktop#7]
As the GNOME 45 beta shell has been stabilized now, it's time to add support for it.

**Comment by jikamens** [comment]
I will take care of this once screen sharing actually works for me in the OS dist I'm running (Ubuntu Mantic). Ref: https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/2033902

**Comment by jikamens** [comment]
New version uploaded, just waiting for them to review and approve it.

**Comment by Jai-GAY** [comment]
Hi

If anyone faced the same issue that [cannot be installed on Ubuntu 22.04.3 LTS 64-bit on Pi](https://github.com/jikamens/allow-locked-remote-desktop/issues/8), the following method works.

[sudo apt-get install gnome-shell-extension-manager](https://askubuntu.com/questions/1453957/maintaining-rdp-connection-to-ubuntu-after-ubuntu-screen-times-out-goes-black) + Install the Allow Locked Remote Desktop Extension.

![22 04 3 64-bit_lockout_issue_2](https://github.com/jikamens/allow-locked-remote-desktop/assets/12781023/c64186aa-33a0-4347-aaa6-3cae6affc17d)

**Comment by jikamens** [comment]
@Jai-GAY PLEASE STOP POSTING IN THIS REPOSITORY ABOUT GENERIC GNOME SUPPORT STUFF THAT IS NOT SPECIFICALLY RELATED TO THIS EXTENSION.

I told you not to do that in the other ticket, and you ignored me and did it again, so I locked the conversation. You STILL didn't get the message again, but instead came over to this completely irrelevant other ticket and posted about it here.

STOP IT or I will report you to GitHub for abuse.
