### ISSUE TITLE
no install dailog box instead Open xdg-open

### ISSUE THREAD

**Issue by Jai-GAY** [jikamens/allow-locked-remote-desktop#8]
How do I get it installed with Ubuntu 22.04.03? My VNC remote desktop session still gets into a problem after the session is locked out. Anything got to do with the windowing system, Wayland ad x11?

Chromium Version 120.0.6099.71 (Official Build) snap (64-bit)

<img width="710" alt="image" src="https://github.com/jikamens/allow-locked-remote-desktop/assets/12781023/44111461-2cbe-4171-b42a-cf71196ddbfe">

**Comment by jikamens** [comment]
This is not a GNOME support forum, it's a bug-tracking system. You're not reporting a bug.
There's a banner right there in your screenshot telling you that you don't have the necessary connector installed in your OS to be able to install extensions on extensions.gnome.org.
Please console the GNOME documentation for how to fix that.

**Comment by Jai-GAY** [comment]
noted, but the connector Package is available [for Ubuntu **23.04** and newer](https://wiki.gnome.org/action/show/Projects/GnomeShellIntegration/Installation?action=show&redirect=Projects%2FGnomeShellIntegrationForChrome%2FInstallation#Ubuntu_Linux): gnome-browser-connector. I am using 22.04 OS.

Too bad, the forum is up to the standard.
<img width="804" alt="image" src="https://github.com/jikamens/allow-locked-remote-desktop/assets/12781023/5dfaad9f-2959-42d6-86d7-d268d07e66cb">
